### ISSUE TITLE
Support asdf (`.tool-versions`)

### ISSUE THREAD

**Issue by puku0x** [nrwl/nx-cloud-workflows#70]
[actions/setup-node](https://github.com/actions/setup-node) supports an option `node-version-file: '.tool-versions'`.

Currently `nrwl/nx-cloud-workflows/v4/workflow-steps/install-node/main.yaml` supports nvm but it would be nice to have another option to support [asdf](https://asdf-vm.com/) .

```
# .tool-versions
nodejs 20.17.0
```
```yml
- name: Checkout
  uses: 'nrwl/nx-cloud-workflows/v4/workflow-steps/checkout/main.yaml'
- name: Setup Node.js
  script: |
    git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.14.1
    export ASDF_DIR=$HOME/.asdf
    source $ASDF_DIR/asdf.sh
    asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    asdf install nodejs
- name: Restore NPM Cache
  uses: 'nrwl/nx-cloud-workflows/v4/workflow-steps/cache/main.yaml'
  inputs:
    key: '.tool-versions'
    paths: ~/.npm
    base_branch: 'develop'
```
