### ISSUE TITLE
node_modules caching is harmfull when using npm ci

### ISSUE THREAD

**Issue by WolfSoko** [nrwl/nx-cloud-workflows#75]
Beside caching node_modules with your caching workflow step the Agents for my repo needed always too long to run [install-node-modules](https://github.com/nrwl/nx-cloud-workflows/tree/main/workflow-steps/install-node-module) action. 

The problem is, that you use `npm ci` to install node_modules based on the `package-lock.json`.  
In an CI environment this sound correct, but the caching of node_modules folder makes no sense at all. It even takes more time because
due to npm documentation `npm ci` deletes the node_modules folder for a clean installation process.  @see [npm ci documentation](https://docs.npmjs.com/cli/v10/commands/npm-ci#description)

What can be cached is the global node cache (`$HOME/.npm`) from which npm ci can pull the packages faster.

I created my agents based on your runner templates. So I guess a lot of people are facing the same problem.

**Comment by JamesHenry** [comment]
The actions/cache documentation also say that it is recommended to not cache node_modules and instead cache the central cache (path dependent on OS): https://github.com/actions/cache/blob/main/examples.md#node---npm

@barbados-clemens please can you take a look?

**Comment by WolfSoko** [comment]
@JamesHenry  That is exactly what the github setup-node action does when caching is configured to npm.

It leverages `npm config get cache` to determine the central cache folder and only caches that.

**Comment by WolfSoko** [comment]
@rarmatei  did you make any progress on this topic?

**Comment by rarmatei** [comment]
> [@rarmatei](https://github.com/rarmatei) did you make any progress on this topic?

@WolfSoko apologies about the late reply, I missed this thread. This has been fixed and the docs were updated a couple of months ago with recommendations on caching the `~/.npm` folder: https://nx.dev/ci/reference/launch-templates#full-example

We need to use the official NPM recommendations on caching, but if you want you can try caching the `node_modules` folder in your pipelines, like you explained above:

```
- name: Cache everything
- name: Cache everything
        uses: 'nrwl/nx-cloud-workflows/v5/workflow-steps/cache/main.yaml'
        inputs:
          key: 'package-lock.json'
          paths: |
            ~/.npm
            node_modules
- name: NPM Install
   script: npm install
- script: ./check-lockfile-and-run-npm-ci.sh
```
